#!/usr/bin/env node
/**
 * Ensure root `.env` exists. WebUI deployment-key authentication is disabled.
 */
import { copyFileSync, existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');
if (!existsSync(envPath)) {
  if (existsSync(examplePath)) {
    copyFileSync(examplePath, envPath);
  } else {
    writeFileSync(envPath, '# Generated by scripts/ensure-env.mjs\nPORT=8172\n', 'utf8');
  }
  console.log('First run: created .env. WebUI opens without a deployment key.');
}
