#!/usr/bin/env node
/**
 * Ensure root `.env` exists. On first run (missing file or placeholder key),
 * generate a random WEBUI_API_KEY and print it once for login.
 */
import { randomBytes } from 'node:crypto';
import { copyFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');
const PLACEHOLDER = 'change-me-to-a-random-secret';

function generateKey() {
  return randomBytes(24).toString('base64url');
}

function readEnv(path) {
  if (!existsSync(path)) return '';
  return readFileSync(path, 'utf8');
}

function upsertKey(content, key) {
  if (/^WEBUI_API_KEY=/m.test(content)) {
    return content.replace(/^WEBUI_API_KEY=.*$/m, `WEBUI_API_KEY=${key}`);
  }
  const prefix = content.trimEnd();
  return `${prefix}${prefix ? '\n' : ''}WEBUI_API_KEY=${key}\n`;
}

let created = false;
let rotated = false;
let content = readEnv(envPath);

if (!content) {
  if (existsSync(examplePath)) {
    copyFileSync(examplePath, envPath);
    content = readEnv(envPath);
  } else {
    content = `# Generated by scripts/ensure-env.mjs\nPORT=8172\n`;
  }
  created = true;
}

const match = content.match(/^WEBUI_API_KEY=(.*)$/m);
const current = match?.[1]?.trim() ?? '';
const needsKey =
  !current || current === PLACEHOLDER || current === 'your-secret-key';

let key = current;
if (needsKey) {
  key = generateKey();
  content = upsertKey(content, key);
  writeFileSync(envPath, content, 'utf8');
  rotated = true;
}

if (created || rotated) {
  console.log('');
  console.log('============================================================');
  console.log(
    created
      ? 'First run: created .env and generated WEBUI_API_KEY'
      : 'Replaced placeholder WEBUI_API_KEY with a random secret',
  );
  console.log(`WEBUI_API_KEY=${key}`);
  console.log('Use this value to log in to the Web UI.');
  console.log('It is stored in .env — keep it private.');
  console.log('============================================================');
  console.log('');
}
